spring:
  datasource:
    url: jdbc:mysql://8.209.119.171:3306/white_jotter?serverTimezone=UTC
    username: root
    password: Zxcv569692?

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 1MB
logging:
  level:
    root: info
    com.donald: debug