spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://8.209.119.171:3306/white_jotter?serverTimezone=UTC
    username: root
    password: Zxcv569692?

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  servlet:
    multipart:
      max-file-size: 1MB
logging:
  level:
    root: warn
    com.donald: info