spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://8.209.119.171:3306/white_jotter?serverTimezone=UTC
    username: root
    password: Zxcv569692?
    hikari:
      connection-timeout: 30000
      minimum-idle: 3
      maximum-pool-size: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-test-query: SELECT 1
      auto-commit: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  servlet:
    multipart:
      max-file-size: 1MB
logging:
  level:
    root: warn
    com.donald: info