spring:
  datasource:
    url: jdbc:mysql://localhost:3306/white_jotter?serverTimezone=UTC
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    root: info
    com.donald: debug