spring:
  datasource:
    url: jdbc:mysql://8.209.119.171:3306/white_jotter?serverTimezone=UTC
    username: root
    password: Zxcv569692?
    hikari:
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 15
      idle-timeout: 30000
      max-lifetime: 1800000
      auto-commit: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 1MB
  redis:
    host: localhost
    port: 6379
    timeout: 2000
  data:
    redis:
      repositories:
        enabled: false
logging:
  level:
    root: info
    com.donald: debug